version: '3'
services:
  backend:
    image: node
    build: .
    container_name: fortuna_back
    working_dir: /app
    command: bash
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    depends_on:
      - database
  database:
    image: mysql
    container_name: fortuna_db
    ports:
      - 3306:3306
    volumes:
      - dbvolume:/var/lib/mysql
volumes:
  dbvolume: